app.home=/opt/ruisui-bank-sim
webfe.tuxedo.client.mode=jolt
webfe.tuxedo.jolt.listen=//127.0.0.1:8000
webfe.tuxedo.jolt.timeoutMillis=30000
reference.dicts=conf/dicts.properties
reference.banks=conf/banks.properties
