#ifndef CNAPS_ERROR_H
#define CNAPS_ERROR_H

#define CNAPS_RESP_SUCCESS "0000"
#define CNAPS_RESP_REQUIRED_FIELD "2001"
#define CNAPS_RESP_FIELD_FORMAT "2002"
#define CNAPS_RESP_DICT_INVALID "2003"
#define CNAPS_RESP_NOT_FOUND "3001"
#define CNAPS_RESP_STATUS_NOT_ALLOWED "3002"
#define CNAPS_RESP_DB_ERROR "4001"
#define CNAPS_RESP_TUXEDO_TIMEOUT "4002"
#define CNAPS_RESP_TUXEDO_UNAVAILABLE "4003"
#define CNAPS_RESP_UNKNOWN "9999"

const char *cnaps_error_message(const char *resp_code);

#endif
