#ifndef CNAPS_FIELDS_H
#define CNAPS_FIELDS_H

#define CNAPS_F_REQUEST_ID "REQUEST_ID"
#define CNAPS_F_REQ_ID "REQ_ID"
#define CNAPS_F_OPERATOR_NO "OPERATOR_NO"
#define CNAPS_F_BRANCH_NO "BRANCH_NO"
#define CNAPS_F_WORK_DATE "WORK_DATE"
#define CNAPS_F_BILL_ID "BILL_ID"
#define CNAPS_F_SERIAL_NO "SERIAL_NO"
#define CNAPS_F_BUSINESS_TYPE "BUSINESS_TYPE"
#define CNAPS_F_AMOUNT "AMOUNT"
#define CNAPS_F_STATUS "STATUS"
#define CNAPS_F_RESP_CODE "RESP_CODE"
#define CNAPS_F_RESP_MSG "RESP_MSG"

#endif
