-- SQL*Plus script for preparing the CNAPS POC schema user.
-- Override these values at execution time:
--   sqlplus / as sysdba @001_create_user.sql CNAPS_POC "change_me" USERS TEMP

DEFINE CNAPS_USER = '&1'
DEFINE CNAPS_PASSWORD = '&2'
DEFINE CNAPS_DEFAULT_TABLESPACE = '&3'
DEFINE CNAPS_TEMP_TABLESPACE = '&4'

CREATE USER &CNAPS_USER IDENTIFIED BY "&CNAPS_PASSWORD"
  DEFAULT TABLESPACE &CNAPS_DEFAULT_TABLESPACE
  TEMPORARY TABLESPACE &CNAPS_TEMP_TABLESPACE;

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO &CNAPS_USER;
ALTER USER &CNAPS_USER QUOTA UNLIMITED ON &CNAPS_DEFAULT_TABLESPACE;
