CREATE UNIQUE INDEX UK_CNAPS_BILL_POC_SERIAL
  ON T_CNAPS_BILL_POC(WORK_DATE, BRANCH_NO, SERIAL_NO);

CREATE INDEX IDX_CNAPS_BILL_POC_QRY
  ON T_CNAPS_BILL_POC(WORK_DATE, BRANCH_NO, STATUS, OPERATOR_NO, SERIAL_NO);
