DECLARE
  V_COLUMN_COUNT NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_COLUMN_COUNT
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'T_CNAPS_BILL_POC'
     AND COLUMN_NAME = 'PAYER_ADDRESS';
  IF V_COLUMN_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE T_CNAPS_BILL_POC ADD (PAYER_ADDRESS VARCHAR2(256 CHAR))';
  END IF;

  SELECT COUNT(*) INTO V_COLUMN_COUNT
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'T_CNAPS_BILL_POC'
     AND COLUMN_NAME = 'PAYEE_ADDRESS';
  IF V_COLUMN_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE T_CNAPS_BILL_POC ADD (PAYEE_ADDRESS VARCHAR2(256 CHAR))';
  END IF;

  SELECT COUNT(*) INTO V_COLUMN_COUNT
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'T_CNAPS_BILL_POC'
     AND COLUMN_NAME = 'PAYER_BANK_NAME';
  IF V_COLUMN_COUNT = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE T_CNAPS_BILL_POC ADD (PAYER_BANK_NAME VARCHAR2(128 CHAR))';
  END IF;
END;
/
