SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

DECLARE
  V_BEFORE NUMBER;
  V_AFTER  NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_BEFORE
    FROM T_CNAPS_BILL_POC
   WHERE STATUS = '00_DRAFT';

  UPDATE T_CNAPS_BILL_POC
     SET STATUS = '10_PENDING_REVIEW',
         CHECKER_NO = NULL,
         CHECKER_TIME = NULL,
         REVIEW_COMMENT = NULL,
         REJECT_REASON = NULL,
         UPDATED_AT = SYSTIMESTAMP,
         VERSION_NO = NVL(VERSION_NO, 1) + 1
   WHERE STATUS = '00_DRAFT';

  SELECT COUNT(*) INTO V_AFTER
    FROM T_CNAPS_BILL_POC
   WHERE STATUS = '00_DRAFT';

  DBMS_OUTPUT.PUT_LINE('draft_before=' || V_BEFORE);
  DBMS_OUTPUT.PUT_LINE('draft_after=' || V_AFTER);

  IF V_AFTER <> 0 THEN
    RAISE_APPLICATION_ERROR(-20001, '00_DRAFT rows remain');
  END IF;
END;
/

COMMIT;
